production_url : 'http://ajourneyinerrors.nfshost.com'

_root:
  layout: default

blog:
  layout: default
  sort : ["date", "desc"]
  paginator:
    enable: true
    sort: ["date", "desc"]
    per_page: 5

tutorials:
  layout: default
  sort : ["date", "desc"]
  paginator:
    enable: true
    sort: ["date", "desc"]
    per_page: 5

widgets :
  google_prettify :
    use : default
    enable : false

asset_pipeline:
  enable: true